export interface Product {
  id: number
  name: string
  description: string
  price: number
  originalPrice: number
  image: string
  category: string
  details: string
  features: string[]
}

export const collections = [
  { id: "couples", name: "Couples", icon: "Heart", count: 24 },
  { id: "superheroes", name: "Superheroes", icon: "Zap", count: 18 },
  { id: "professionals", name: "Professionals", icon: "Briefcase", count: 20 },
  { id: "wedding", name: "Wedding", icon: "Sparkles", count: 16 },
  { id: "family", name: "Family", icon: "Users", count: 15 },
  { id: "hobbies", name: "Hobbies", icon: "Trophy", count: 22 },
  { id: "sports", name: "Sports", icon: "Dumbbell", count: 14 },
  { id: "music", name: "Music", icon: "Music", count: 12 },
  { id: "travel", name: "Travel", icon: "Plane", count: 10 },
  { id: "pets", name: "With Pets", icon: "Heart", count: 13 },
  { id: "vehicles", name: "With Vehicles", icon: "Car", count: 16 },
  { id: "fantasy", name: "Fantasy", icon: "Sparkles", count: 11 },
]

export const allProducts: Product[] = [
  // Couples Collection
  {
    id: 1,
    name: "Romantic Couple",
    description: "Classic couple figurine in casual attire",
    price: 1599,
    originalPrice: 2199,
    image: "/romantic-couple-figurine-standing-together.jpg",
    category: "couples",
    details: "Perfect anniversary or Valentine's gift with customizable faces and outfits",
    features: ["Hand-painted details", "Customizable clothing", "Premium resin material", "Free name plate"],
  },
  {
    id: 2,
    name: "Dancing Couple",
    description: "Couple in elegant dancing pose",
    price: 1799,
    originalPrice: 2399,
    image: "/dancing-couple-figurine-ballroom.jpg",
    category: "couples",
    details: "Elegant figurine capturing the romance of dance",
    features: ["Dynamic pose", "Detailed clothing", "Stable base", "Gift box included"],
  },
  {
    id: 3,
    name: "Beach Couple",
    description: "Couple in beachwear holding hands",
    price: 1699,
    originalPrice: 2299,
    image: "/beach-couple-figurine-vacation.jpg",
    category: "couples",
    details: "Capture your beach vacation memories forever",
    features: ["Beach theme accessories", "Waterproof coating", "Custom faces", "Sand base option"],
  },
  {
    id: 4,
    name: "Movie Night Couple",
    description: "Couple on couch with popcorn",
    price: 1599,
    originalPrice: 2099,
    image: "/couple-on-couch-watching-movie-figurine.jpg",
    category: "couples",
    details: "Perfect for movie lovers and cozy nights in",
    features: ["Miniature couch", "Popcorn accessory", "Detailed expressions", "Custom clothing"],
  },

  // Superheroes Collection
  {
    id: 5,
    name: "Flying Hero",
    description: "Superman-style superhero in flight",
    price: 999,
    originalPrice: 1599,
    image: "/flying-superhero-figurine-cape.jpg",
    category: "superheroes",
    details: "Transform into a flying superhero with customizable face",
    features: ["Dynamic flying pose", "Removable cape", "Custom face sculpt", "Display stand"],
  },
  {
    id: 6,
    name: "Wonder Woman Style",
    description: "Powerful female superhero",
    price: 999,
    originalPrice: 1599,
    image: "/wonder-woman-superhero-figurine-female.jpg",
    category: "superheroes",
    details: "Celebrate strength and power with this iconic pose",
    features: ["Battle stance", "Detailed armor", "Custom face", "Premium paint job"],
  },
  {
    id: 7,
    name: "Superhero Duo",
    description: "Two superheroes side by side",
    price: 1899,
    originalPrice: 2699,
    image: "/two-superheroes-together-figurine.jpg",
    category: "superheroes",
    details: "Perfect for couples or best friends as superheroes",
    features: ["Two figurines", "Mix and match powers", "Custom faces", "Shared base"],
  },

  // Professionals Collection
  {
    id: 8,
    name: "Doctor",
    description: "Medical professional with stethoscope",
    price: 999,
    originalPrice: 1499,
    image: "/doctor-figurine-with-stethoscope-white-coat.jpg",
    category: "professionals",
    details: "Honor the medical heroes in your life",
    features: ["White coat", "Medical accessories", "Custom face", "Name tag option"],
  },
  {
    id: 9,
    name: "Teacher",
    description: "Educator with books and pointer",
    price: 999,
    originalPrice: 1499,
    image: "/teacher-figurine-with-books-classroom.jpg",
    category: "professionals",
    details: "Perfect gift for teachers and educators",
    features: ["Books accessory", "Pointer stick", "Custom outfit", "Desk base option"],
  },
  {
    id: 10,
    name: "Chef",
    description: "Culinary expert with chef hat",
    price: 999,
    originalPrice: 1499,
    image: "/chef-figurine-with-hat-cooking-utensils.jpg",
    category: "professionals",
    details: "Great for professional chefs or cooking enthusiasts",
    features: ["Chef hat and apron", "Cooking utensils", "Custom face", "Kitchen base"],
  },
  {
    id: 11,
    name: "Businessman",
    description: "Corporate professional in suit",
    price: 999,
    originalPrice: 1499,
    image: "/businessman-figurine-suit-briefcase.jpg",
    category: "professionals",
    details: "Perfect for executives and business professionals",
    features: ["Business suit", "Briefcase", "Custom face", "Office desk base"],
  },

  // Wedding Collection
  {
    id: 12,
    name: "Classic Wedding Cake Topper",
    description: "Bride and groom in formal attire",
    price: 1999,
    originalPrice: 2799,
    image: "/wedding-cake-topper-bride-groom.jpg",
    category: "wedding",
    details: "Traditional wedding cake topper with custom faces",
    features: ["Wedding dress details", "Tuxedo", "Custom faces", "Stable base for cake"],
  },
  {
    id: 13,
    name: "Beach Wedding",
    description: "Bride and groom in beach attire",
    price: 1999,
    originalPrice: 2799,
    image: "/beach-wedding-couple-figurine-casual.jpg",
    category: "wedding",
    details: "Perfect for destination beach weddings",
    features: ["Casual wedding attire", "Beach accessories", "Custom faces", "Sand base"],
  },
  {
    id: 14,
    name: "Indian Wedding",
    description: "Couple in traditional Indian wedding attire",
    price: 2199,
    originalPrice: 2999,
    image: "/indian-wedding-couple-figurine-traditional-dress.jpg",
    category: "wedding",
    details: "Celebrate Indian wedding traditions",
    features: ["Traditional outfits", "Jewelry details", "Custom faces", "Decorative base"],
  },

  // Family Collection
  {
    id: 15,
    name: "Family of Three",
    description: "Parents with one child",
    price: 2299,
    originalPrice: 3199,
    image: "/family-of-three-figurine-parents-child.jpg",
    category: "family",
    details: "Capture your family memories in miniature",
    features: ["Three figurines", "Custom faces", "Age-appropriate sizing", "Family base"],
  },
  {
    id: 16,
    name: "Family of Four",
    description: "Parents with two children",
    price: 2799,
    originalPrice: 3799,
    image: "/placeholder.svg?height=400&width=400",
    category: "family",
    details: "Complete family set with customization",
    features: ["Four figurines", "Custom faces", "Mix boy/girl kids", "Large display base"],
  },

  // Hobbies Collection
  {
    id: 17,
    name: "Guitarist",
    description: "Rock star with electric guitar",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "hobbies",
    details: "For music lovers and guitarists",
    features: ["Detailed guitar", "Rock pose", "Custom face", "Stage base option"],
  },
  {
    id: 18,
    name: "Photographer",
    description: "Person with professional camera",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "hobbies",
    details: "Perfect gift for photography enthusiasts",
    features: ["Camera accessory", "Photography pose", "Custom face", "Tripod option"],
  },
  {
    id: 19,
    name: "Gamer",
    description: "Gaming enthusiast with controller",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "hobbies",
    details: "For dedicated gamers and esports fans",
    features: ["Gaming controller", "Headset", "Custom face", "Gaming chair base"],
  },
  {
    id: 20,
    name: "Artist/Painter",
    description: "Creative with easel and palette",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "hobbies",
    details: "Celebrate artistic creativity",
    features: ["Mini easel", "Paint palette", "Brush", "Custom face"],
  },

  // Sports Collection
  {
    id: 21,
    name: "Cricket Player",
    description: "Batsman in action pose",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "sports",
    details: "For cricket fans and players",
    features: ["Cricket bat", "Action pose", "Team colors", "Custom face"],
  },
  {
    id: 22,
    name: "Football Player",
    description: "Soccer player with ball",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "sports",
    details: "Perfect for football enthusiasts",
    features: ["Soccer ball", "Jersey customization", "Action pose", "Custom face"],
  },
  {
    id: 23,
    name: "Gym Enthusiast",
    description: "Fitness lover with dumbbells",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "sports",
    details: "Motivational gift for fitness lovers",
    features: ["Dumbbells", "Athletic wear", "Muscular build option", "Custom face"],
  },

  // Music Collection
  {
    id: 24,
    name: "DJ",
    description: "DJ with turntables and headphones",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "music",
    details: "For DJs and electronic music producers",
    features: ["DJ equipment", "Headphones", "Custom face", "DJ booth base"],
  },
  {
    id: 25,
    name: "Drummer",
    description: "Drummer with drum kit",
    price: 1199,
    originalPrice: 1799,
    image: "/placeholder.svg?height=400&width=400",
    category: "music",
    details: "Perfect for drummers and percussion lovers",
    features: ["Mini drum kit", "Drumsticks", "Custom face", "Stage setup"],
  },

  // Travel Collection
  {
    id: 26,
    name: "World Traveler",
    description: "Explorer with backpack and map",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "travel",
    details: "For adventurers and travel enthusiasts",
    features: ["Backpack", "Travel accessories", "Custom face", "Globe base option"],
  },
  {
    id: 27,
    name: "Pilot",
    description: "Aviator in pilot uniform",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "travel",
    details: "Honor pilots and aviation professionals",
    features: ["Pilot uniform", "Cap", "Custom face", "Airplane base"],
  },

  // Pets Collection
  {
    id: 28,
    name: "With Dog",
    description: "Person with pet dog",
    price: 1299,
    originalPrice: 1899,
    image: "/placeholder.svg?height=400&width=400",
    category: "pets",
    details: "Include your furry friend in your figurine",
    features: ["Custom dog breed", "Leash option", "Custom face", "Park base"],
  },
  {
    id: 29,
    name: "With Cat",
    description: "Person holding pet cat",
    price: 1299,
    originalPrice: 1899,
    image: "/placeholder.svg?height=400&width=400",
    category: "pets",
    details: "Perfect for cat lovers",
    features: ["Custom cat color", "Holding pose", "Custom face", "Home base"],
  },

  // Vehicles Collection
  {
    id: 30,
    name: "Biker with Motorcycle",
    description: "Person on custom motorcycle",
    price: 1599,
    originalPrice: 2299,
    image: "/placeholder.svg?height=400&width=400",
    category: "vehicles",
    details: "For motorcycle enthusiasts",
    features: ["Detailed bike", "Riding pose", "Custom face", "Road base"],
  },
  {
    id: 31,
    name: "Car Lover",
    description: "Person with sports car",
    price: 1599,
    originalPrice: 2299,
    image: "/placeholder.svg?height=400&width=400",
    category: "vehicles",
    details: "Perfect for car enthusiasts",
    features: ["Sports car model", "Custom car color", "Custom face", "Garage base"],
  },

  // Fantasy Collection
  {
    id: 32,
    name: "Angel",
    description: "Figure with angel wings",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "fantasy",
    details: "Ethereal angel design",
    features: ["Large wings", "Halo", "Flowing robes", "Custom face"],
  },
  {
    id: 33,
    name: "Wizard",
    description: "Magical wizard with staff",
    price: 999,
    originalPrice: 1599,
    image: "/placeholder.svg?height=400&width=400",
    category: "fantasy",
    details: "For fantasy and magic lovers",
    features: ["Wizard robe", "Magic staff", "Custom face", "Mystical base"],
  },
]

export function getProductsByCategory(category: string): Product[] {
  return allProducts.filter((p) => p.category === category)
}

export function getProductById(id: number): Product | undefined {
  return allProducts.find((p) => p.id === id)
}
